server {
    listen 443 ssl default_server; # <-- Магия здесь: default_server
    server_name _;                 # <-- Символ "_" значит "любое имя"

    # Нам всё равно нужны сертификаты, чтобы установить SSL-соединение и отказать
    ssl_certificate /etc/ssl/cloudflare.pem;
    ssl_certificate_key /etc/ssl/cloudflare.key;

    # Вариант 1: Просто разорвать соединение (Для хакеров)
    return 444; 
    
    # Вариант 2: Вернуть 404 (Более вежливо)
    # return 404;
}

# Блок для Yamtrack
server {
    listen 443 ssl;
    server_name anime.web-socket-test-bench.site;

    # Сертификаты (Origin Certs от Cloudflare)
    ssl_certificate /etc/ssl/cloudflare.pem; 
    ssl_certificate_key /etc/ssl/cloudflare.key;

    location / {
        proxy_pass http://yamtrack:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# Блок для Grafana
server {
    listen 443 ssl;
    server_name monitor.web-socket-test-bench.site;

    ssl_certificate /etc/ssl/cloudflare.pem;
    ssl_certificate_key /etc/ssl/cloudflare.key;

    location / {
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
